sudo: false
language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

jobs:
  include:
    - stage: game
      script: 
        - cd apps/game
        - make build
    - stage: battle
      script: 
        - cd apps/battle
        - make build

install:
  - go mod download

