sudo: false
language: go

go:
  - 1.18.x

env:
  - GO111MODULE=on

jobs:
  include:
    - stage: game
      script: 
        - cd apps/game
        - make build
    - stage: gate
      script: 
        - cd apps/gate
        - make build

install:
  - go mod download

