# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

clone:
  depth: 1
  enabled: true

pipelines:
  default:
    - step:
        name: 'generate server go code'
        image: golang:1.15
        script:
          - pwd
          - apt-get update
          # Add python pip and bash
          - apt-get -y install python3-minimal python3-pip
          # Install docker-compose via pip
          - pip3 install docker-compose

          - docker-compose run --service-ports -d mongo
          - docker-compose run --service-ports -d rejson
          - make test
        services:
          - docker
        caches:
          - docker
