# config.toml

title = "gate_config"

debug = true
log_level = "warn"

# ip and port
gate_id = 101
https_listen_addr = ":443"
http_listen_addr = ":80"

# tls config
cert_path_debug = "config/cert/localhost.crt"
key_path_debug = "config/cert/localhost.key"

cert_path_release = "config/cert/localhost.crt"
key_path_release = "config/cert/localhost.key"

# db
db_dsn = "mongodb://localhost:27017"
database = "db_gate"
redis_addr = "localhost:6379"

# gate evironment 线上环境不能用mdns作为registry，并发高的情况下会出现找不到服务的bug
registry_debug = "consul"
registry_address_debug = "localhost:8500"
broker_debug = "memory"

registry_release = "consul"
registry_address_release = "host.docker.internal:8500"
broker_release = "nsq"
broker_address_release = "localhost:4150" 
