# config.toml

title = "yokai_gate_config"

gate_id = 2001
db_dsn = "mongodb://localhost:27017"
database = "db_gate"
http_listen_addr = ":8081"

# gate evironment
registry = "mdns"
transport = "tcp"
broker = "nsq"
