# config.toml

title = "yokai_battle_config"

battle_id = 2001
db_dsn = "mongodb://localhost:27017"
database = "db_battle"
http_listen_addr = ":8081"

# battle evironment
registry = "mdns"
transport = "http"
broker = "http"
