# config.toml

title = "yokai_game_config"

game_id = 1001
account_connect_max = 5000
account_timeout = "20s"
db_dsn = "mongodb://localhost:27017"
database = "db_game"
http_listen_addr = ":8080"
tcp_listen_addr = ":7030"

# game evironment
registry = "mdns"
transport = "tcp"
broker = "nsq"
