# config.toml

title = "yokai_config"

[game]
game_id = 1001
client_connect_max = 5000
client_timeout = 10
heart_beat = 10
mysql_dsn = "root:@(127.0.0.1:3306)/db_yokai"
http_listen_addr = ":8080"
tcp_listen_addr = ":7030"

# micro service
[game evn]
transport = "tcp"
