name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: build and push
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: make build

    - name: install docker plugins
      run: docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions

    - name: Run MongoDB Docker Containers
      run: docker-compose run --service-ports -d mongo

    - name: Run Rejson Docker Containers
      run: docker-compose run --service-ports -d rejson

    - name: Test
      run: sudo make test
 
    - name: Docker
      run: make docker

    - name: Docker login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    
    - name: Docker tag and push
      run: make push_github
